### ISSUE TITLE
Visual studio 2017 with TFS 2013 - error related to build tools 

### ISSUE THREAD

**Issue by harshaldeshpande** [brody2consult/cordova-sqlite-ext#70] opened 2017-11-13 09:30 UTC
Hello Team,
I am trying to take a build in Visual studio 2017 and connected it to TFS 2013,but after queuing a build i am getting an error which is as given below
"C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets (57): The build tools for v141 (Platform Toolset = 'v141') cannot be found."

I have tried solutions which are provided on google could you please suggest how to overcome this issue.

**Comment by brody2consult** [comment] 2017-12-11 15:33
Thanks for reporting, looks like a duplicate of litehelpers/cordova-sqlite-ext#60. Possible workaround is described in <https://developercommunity.visualstudio.com/content/problem/48806/cant-find-v140-in-visual-studio-2017.html>. Will be fixed in the near future.

**Closed as completed by brody2consult** 2017-12-11 15:33 UTC
Labels: bug-general, duplicate, question, testing

**Comment by brody2consult** [comment] 2017-12-27 04:02
Issue should be now be resolved as discussed in #60.
